from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ComponentContract(Protocol):
    component_id: str
    name: str
    version: str
    status: str

    def initialize(self) -> bool: ...
    def start(self) -> bool: ...
    def stop(self) -> bool: ...
    def validate(self) -> dict[str, Any] | bool: ...
    def get_manifest(self) -> dict[str, Any]: ...
    def get_status(self) -> dict[str, Any]: ...
    def get_health(self) -> dict[str, Any]: ...
    def get_statistics(self) -> dict[str, Any]: ...
    def report(self) -> dict[str, Any]: ...
