from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class KernelContextContract(Protocol):
    def register_service(self, name: str, service: Any, **kwargs: Any) -> bool: ...
    def get_service(self, name: str) -> Any | None: ...
    def set_runtime(self, name: str, value: Any, **kwargs: Any) -> bool: ...
    def get_runtime(self, name: str, default: Any = None) -> Any: ...
    def add_timeline_event(self, event_type: str, payload: dict[str, Any] | None = None) -> bool: ...
